### ISSUE TITLE
Composer Platform Check Bug

### ISSUE THREAD

**Issue by prussobcm** [timber/starter-theme#165]
Hi there,
I hope someone can help me with the following issue.

I'm running a WordPress project in Docker Container. This is the `docker-compose.yml` file:

```
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8888:80"
    restart: "no"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
    working_dir: /var/www/html
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
  db_data: {}
```

After creating `Conatiner` and `Image` I run the following command inside the themes folder `composer create-project upstatement/timber-starter-theme --no-dev` to install the theme.

When I activate the theme I get a fatal error saying `Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".`

I checked globally and locally and my PHP version is 8.1.6. Is there a way to fix this issue? Please note that I'm not getting this error if I use an old version of this theme that I have previously used in another WP project.
